In [2]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:

df = pd.read_csv("C:\\Users\\Admin\\\Downloads\\Salary_Data.csv")

X = df.iloc[:,0:1].values
y = df.iloc[:,1].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =.25,random_state=0)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train  = sc_X.fit_transform(X_train)
X_test  = sc_X.fit_transform(X_test)


from sklearn.naive_bayes import GaussianNB
Classifier = GaussianNB()

Classifier.fit(X_train,y_train)

y_pred = Classifier.predict(X_test)
print(y_test)
print(y_pred)



[ 37731. 122391.  57081.  63218. 116969. 109431. 112635.  55794.]
[ 39343. 101302.  60150.  56642.  98273.  91738.  98273.  60150.]


In [8]:
# 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("C:\\Users\\Admin\\\Downloads\\Salary_Data.csv")

X = df.iloc[:,0:1].values
y = df.iloc[:,1].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =.25,random_state=0)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train  = sc_X.fit_transform(X_train)
X_test  = sc_X.fit_transform(X_test)


from sklearn.ensemble import RandomForestClassifier
Classifier = RandomForestClassifier()

Classifier.fit(X_train,y_train)

y_pred = Classifier.predict(X_test)
print(y_test)
print(y_pred)



[ 37731. 122391.  57081.  63218. 116969. 109431. 112635.  55794.]
[ 39343. 101302.  60150.  56642.  98273.  91738.  98273.  60150.]


In [9]:
# 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("C:\\Users\\Admin\\\Downloads\\Salary_Data.csv")

X = df.iloc[:,0:1].values
y = df.iloc[:,1].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =.25,random_state=0)


from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train  = sc_X.fit_transform(X_train)
X_test  = sc_X.fit_transform(X_test)

from sklearn.linear_model import LogisticRegression
Classifier = LogisticRegression()
Classifier.fit(X_train,y_train)  

y_pred = Classifier.predict(X_test)
print(y_test)
print(y_pred)




[ 37731. 122391.  57081.  63218. 116969. 109431. 112635.  55794.]
[ 39343. 121872.  39343.  39343. 121872. 105582. 121872.  39343.]


In [10]:
# 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv("C:\\Users\\Admin\\\Downloads\\Salary_Data.csv")

X = df.iloc[:,0:1].values
y = df.iloc[:,1].values

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.25,random_state=0)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)


from sklearn.svm import SVC 
classifier = SVC()
classifier.fit(X_train,y_train)

y_pred = classifier.predict(X_test)
print(y_test)
print(y_pred)



[ 37731. 122391.  57081.  63218. 116969. 109431. 112635.  55794.]
[ 39343. 101302.  60150.  56642.  98273.  91738.  98273.  60150.]
